### ISSUE TITLE
Unexpected delay when sending messages?

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.TransactionalSession#199] opened 2023-05-08 08:47 UTC
#### Description

In a small [repo app](https://github.com/oskar/TransactionalSessionWithOutbox/blob/main/TransactionalSessionWithOutbox) that I mentioned in two recently created issues, I had to add a `Task.Delay` [before stopping the endpoint](https://github.com/oskar/TransactionalSessionWithOutbox/blob/main/TransactionalSessionWithOutbox/Program.cs#L55), otherwise no message would be sent at all.

With a delay of 4 seconds, the messages are not sent before the application terminates. It surprised me a bit, as 4 seconds is quite some time. It made me wonder if there is any risk of message loss or possibly unexpected latency in the system when using Transactional session.

There is probably an reasonable explanation for this issue (perhaps related to commit duration, implementation detail of the `LearningTransport` or details with the two phases in the Transactional Session), but I haven't figured it out yet.

#### Expected behavior

No need for a `Task.Delay` in repo app, alternatively a shorter delay.

#### Actual behavior

A delay of at least 4 seconds is required.

#### Versions

`NServiceBus` 8.0.3
`NServiceBus.Persistence.Sql.TransactionalSession` 7.0.1
`NServiceBus.TransactionalSession` 2.0.2      
 

### Steps to reproduce

Clone the [repo app](https://github.com/oskar/TransactionalSessionWithOutbox) and change the delay interval.

**Comment by danielmarbach** [comment] 2023-05-10 08:07
@pardahlman 

Some of it is by design and some of it is also related to the poll-based implementation with SQL.

The transactional session implementation uses the existing outbox mechanism already available and it does that by triggering a control message before the outgoing operations are stored. Outgoing operations will be dispatched when the control message arrives. When the control message gets received and there is not `OutboxRecord` for a given `SessionId` the control message will be delayed (potentially a number of times) until, either the `OutboxRecord` is there or the amount of time elapsed from when the message was sent is longer than transaction commit time-out configured for the endpoint. By doing all the heavy lifting inside the message handling pipeline and only sending a tiny control message to trigger that mechanism, we drastically reduce the load on the transport for sending outside the handler and thus slim down the chance for failure or back pressure. Should back pressure happen, then it is more likely to happen during the handling of the incoming message, and therefore we achieve naturally throttling of the outbox record dispatching. Moreover, this approach is naturally scalable even in competing consumer scenarios.

But this has the consequences of having potential slight delays as well as being subjected to busy queues. Some of it is also outlined in https://github.com/Particular/NServiceBus.TransactionalSession/issues/145. The commit delay intervall also plays are role and currently that is not configurable https://github.com/Particular/NServiceBus.TransactionalSession/issues/179. The learning transport with a file-based polling mechanism also has a tendency to exhibit unreliable behavior. 

We have decided against using a poll-based background mechanism (database as a trigger).

## Database as a trigger: No longer doing message operations in the controller

![MessageAsTrigger](https://user-images.githubusercontent.com/174258/161015389-9171501d-ee79-423d-ab11-52c04ca04b12.png)

Instead of sending or publishing a message to the message system, the event is written to the local data store with the same transaction.For non-relational databases that do not support cross-document transactions, the events must be written to the same document. In the background, a message relay service is responsible to query the database or documents for events (by polling or change data capturing) and then publish the messages to the message system.

Pros:
- Integrates well with existing code structures because Read your own Writes is still supported
- Consistency
- Not directly dependent on the availability of the message system
Cons:
- Depending on the chosen approach, the load on the local data storage is large
- Message Relay service is an additional service that needs to be operated and may be difficult to scale (assumption: single instance operation is sufficient with batching)
- Outbox must be consistently enforced even in downstream contexts to avoid phantom and ghost messages.
Assumptions:
- Data storage availability very high and latency low
- Data storage supports transactions

We believe it would also exhibit very similar latency characteristics, but also has further challenges. As a company, we have done our fair share of dealing with the complexity of polling-based dispatches when implementing the timeout manager infrastructure. A polling-based mechanism for the outbox that would only rely on the database for the outgoing message operations outside the handler needs to reimplement large portions of this algorithm that we had in place for the timeout manager. Furthermore, it would require introducing dedicated outbox seam extensions both for peeking and deleting outbox records as well as polling (the message relay) for due records (set-based). Getting this right and efficient has proven to be a challenge with cloud-based storage like Azure Table. Furthermore, a dedicated infrastructure is required to run the polling mechanism, either as a background job or a dedicated sidecar. Scaling this out and making sure this mechanism doesn't interfere with outbox operations as part of the incoming message is far from trivial.

**Comment by pardahlman** [comment] 2023-05-22 11:44
Thanks for the detailed explanation, @danielmarbach 🙏 

I've noticed a similar delay to the one in the repo app when using RabbitMQ, which makes me think that the implementation detail of the LearningTransport is not the culprit. Could it be that we run into the commit delay interval of 2 seconds _every time_ the control message is handled?

Currently I can consistently reproduce that the delay between `ITransactionalSession.Commit()` (using MSSQL outbox) and message being published on RabbitMQ is higher than 3 seconds.

As I re-read your response here and the documentation, I find myself wondering what happens if a session has outbox records with outgoing messages, but the control message fails to be handled within the configured `MaximumCommitDuration`. 

The documentation [for failure scenarios](https://docs.particular.net/nservicebus/transactional-session/#failure-scenarios) suggests that if the transactional session successfully commits, the messages will be published:

> Transaction finishes with data being stored, and outgoing messages eventually sent - when the Commit path successfully stores the OutboxRecord

In the same section it is noted that retries is not applied for the control message:

> It cannot rely on the recoverability mechanism used by the outbox, which uses [retries](https://docs.particular.net/nservicebus/recoverability/) to ensure outgoing messages are dispatched when failures occur

**Comment by danielmarbach** [comment] 2023-05-30 13:38
@pardahlman thank you for your patience. There were quite a few public holidays happening and I traveled to a conference. This kept me occupied a while :(

> Could it be that we run into the commit delay interval of 2 seconds every time the control message is handled?

We have had other customers who ran into the commit delay interval being slightly too high for their use cases. I [opened an issue to address this](https://github.com/Particular/NServiceBus.TransactionalSession/issues/179) in the next minor

> As I re-read your response here and the documentation, I find myself wondering what happens if a session has outbox records with outgoing messages, but the control message fails to be handled within the configured MaximumCommitDuration.

The control message will be moved to the configured error queue. We have a test for that https://github.com/Particular/NServiceBus.TransactionalSession/blob/main/src/NServiceBus.TransactionalSession.AcceptanceTests/When_outbox_entry_becomes_visible_after_tx_timeout.cs#L16

> In the same section it is noted that retries is not applied for the control message:

This section refers to the fact that the control message handling normally never invokes the custom recoverability parts. So for example you cannot use `Recoverability().Delayed(...)` to override anything that the transactional session does. Maybe we can make this part a bit clearer in the documentation. Would you have any suggestions?

**Comment by pardahlman** [comment] 2023-06-07 08:23
No worries, @danielmarbach - it sounds like legit reasons for being away from GitHub for a while!

Thanks for explaining the error handling for the control message. It will create some interesting challenges when deciding whether to re-sending control messages (from Service Pulse) or not as the user might have tried to perform the operation again an succeeded.  A suggestion for clarifying it in the documentation would be to add the following [to the section _Maximum commit duration_](https://docs.particular.net/nservicebus/transactional-session/#usage-advanced-configuration-maximum-commit-duration):

> In practice, the observed total commit time might be longer due to delays in the transport caused by latency, delayed delivery, load on the input queue, endpoint concurrency limits, and more. **If the control message is not successfully handled within the configured commit duration, it will be moved to the error queue**.

It sounds like a great feature to be able to configure the commit delay, but my question remains: is it likely that the control message _always gets delayed_? I've run our integration tests for this scenario multiple times and it never succeeds under 3 seconds. I'm wondering because if that is the reason, it would explain where the majority of the time waiting is spent.

Lastly I want to let you know that we have paused the migration to Transactional Session as the delay discussed here will impact user experience for end users.

**Comment by pardahlman** [comment] 2023-06-07 09:51
@danielmarbach, the session is open and committed in an ASP.NET Core MVC Controller. It is performed in an infrastructure layer and looks something like this:

```csharp
await _transactionalSession.Open(new SqlPersistenceOpenSessionOptions(), ct);
await _commandInvoker.InvokeAsync(command, ct);
await _transactionalSession.Commit(ct);
```

**Comment by danielmarbach** [comment] 2023-06-07 14:06
@pardahlman how does that infrastructure layer make sure the code is only invoked for APIs that actually require the transactional session integration? 

I have recently updated the [ASP.NET Core integration sample](https://docs.particular.net/samples/transactional-session/aspnetcore-webapi/) to leverage a result filter to make sure the session is only used when really required. 
Otherwise, the commit would always send a control message for all other API interactions even when the transactional session is not a play.

That unnecessary might also add to the delay problem.

> is it likely that the control message always gets delayed? I've run our integration tests for this scenario multiple times and it never succeeds under 3 seconds. 

We do the control message dispatch at the beginning of commit. So if the transport is fast enough and there is no huge backlog of messages, it will immediately be picked up and then delayed because the record is not yet there since the outbox tx hasn't completed.

**Comment by pardahlman** [comment] 2023-06-09 06:37
> We do the control message dispatch at the beginning of commit.

I realized this myself after office hours and couldn't find the time to update my comment 🙈 The integration test I'm running use a dedicated RabbitMQ broker, so fast transport and no pending messages in the endpoint queue.

> how does that infrastructure layer make sure the code is only invoked for APIs that actually require the transactional session integration?

The HTTP APIs uses a CQRS design with different applications for commands and queries. It is only the command APIs that uses NServiceBus, and close to all HTTP requests follow the same pattern: make changes in database then publish event. This means that we can open the session for each request and be reasonably sure it will be used.

That being said, there are exceptions to the rule both on application level (commands and queries in same application) as well as route level (certain commands does not use NServiceBus). The filter looks interesting, but we're pretty far away from being able to leverage method injection unfortunately. I'm grateful nonetheless that you mentioned it, as it will be important in future potential redesigns.

**Comment by danielmarbach** [comment] 2023-06-20 06:53
Hmmm... I think this requires a bit more analysis once we start doing further tweaks to the transactional session. We'll keep you posted.

**Comment by ramonsmits** [comment] 2023-07-24 17:19
FYI: The following spike removes the delay:

- https://github.com/Particular/NServiceBus.TransactionalSession/pull/182

**Comment by pardahlman** [comment] 2024-05-23 06:58
Hi @danielmarbach , I'm investigating if it's possible to start using Transactional Session, but this issue still remains a blocker for us. Our analysis is that the 3-4 seconds delay that Transactional Session introduces will have potential consequences that is difficult to foresee.

Do you have any updates on this issue? Is the spike that  @ramonsmits refers to an feasible approach for solving the problem?

**Comment by adamralph** [comment] 2024-05-23 10:23
@pardahlman we'll look into shortening the delay, but in the meantime, why do you believe this is a blocker for you?

Note that there is no risk of message loss. If the application terminates before the message is actually sent, the message will be sent when the application starts again. That is, in fact, one of the main benefits of using Transactional Session.

**Comment by ramonsmits** [comment] 2024-05-23 10:50
> Is the spike that @ramonsmits refers to an feasible approach for solving the problem?

@pardahlman It is, it is the only method to mitigate the delay with SQLT that using polling. The spike will send messages ASAP once the transaction is committed. Any other approach will have additional latency. This method is therefore also faster on any push based transport. You can review the spike changes and see there are no consistency issues.

**Comment by danielmarbach** [comment] 2024-05-23 15:11
> In some scenarios multiple actions are performed in sequence: as soon as one HTTP request completes, the next is sent. It is my understanding that Transactional Session commits and then there is a 3-4 second delay. I know of no way to observe when the messages are in fact sent, so our ASP.NET Core controllers returns when the Transactional Session is committed. This in turn, leads to HTTP request completing before the NServiceBus messages are sent. The concern here is that this behavior may lead to actions being perform in an unexpected order.

@pardahlman What you are describing is a general thing that can happen once you move towards offloading requests to some background processing with messaging and independent from the transactional session. Once you send a message to a queue there can be an arbitrary delay until this message is picked up and the work being done because you offloaded and durably stored the request. Now if you have business processes that assume certain things are happening in sequence plus the steps in that sequence happen at a high pace you might need to rethink the user interaction flow accordingly. 

Of course, in some cases where ordering is assumed, things might self-heal themselves due to retries, and it is OK to rely on in numerous instances but probably not something you to always rely for complex business processes that follow a sequence of steps in a relatively short period. 

FYI I'm not denying here that things can be improved and need to be enhanced in the transactional session I just want to make sure to do it for the right reasons.

**Comment by pardahlman** [comment] 2024-05-27 09:02
Thanks for getting back to me, @danielmarbach 

_I'm arguing below based on the fact that Transactional Session adds roughly 4 seconds between session committing and messages being sent. We've seen this consistently with the repo app linked in this issue._

I agree with your comment above. Our system consists of roughly 90 endpoints, some of which are old/complex. There is no easy way to asses all interaction between endpoints. The fact that the request completes more than 4 seconds before the message is sent will lead to different message flow in some parts, and we're not able to assess the impact of that. This makes us hesitant to migrate. If the delay would be shorter we might not be as skeptical.

As to our critical business flows where low latency is important: we have taken steps in making these flows stable and fast. This include dynamic number of instances to make sure the queue is kept empty/short as well as design decisions in the domain logic. Metrics shows us that when everything works as expected, the delay is roughly 20 ms from publish to consume. Again, adding ~4000 ms to that time is a significant degradation.

**Comment by joeblack3108** [comment] 2024-05-27 10:55
We ran into the same issue and used this hack

```
 RavenDbOpenSessionOptions options = new RavenDbOpenSessionOptions();

 Type optionsType = typeof(RavenDbOpenSessionOptions);
 PropertyInfo? prop = optionsType.GetProperty("CommitDelayIncrement", BindingFlags.NonPublic | BindingFlags.Instance);
 prop?.SetValue(options, TimeSpan.FromSeconds(0.1));

 await _transactionalSession.Open(options);
```

Got the idea from https://github.com/Particular/NServiceBus.TransactionalSession/issues/179 
This solved our problems and seems like it's working fine.

**Comment by adamralph** [comment] 2024-05-29 09:13
@pardahlman thank you for raising this issue. I'm going to close it now, because this is not a bug. The transactional session is behaving as designed. If you would like to be updated on the progress of making the delay configurable, please follow https://github.com/Particular/NServiceBus.TransactionalSession/issues/179. As you can see, there is some movement on that in https://github.com/Particular/NServiceBus.TransactionalSession/pull/330 so hopefully we'll be able to release that feature soon.

If you have any other questions regarding your specific use cases, please don't hesitate to reach to us by requesting either non-critical or critical (as applicable) support at https://particular.net/support

**Closed by adamralph** 2024-05-29 09:13 UTC
Labels: Bug
